name: Pull request- plan

on:
  pull_request:
env:
  TF_LOG: INFO
  TF_INPUT: false

jobs: 
  terraform-plan:
    runs-on: ubuntu-latest
    name: 'Terraform Plan'
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
        run:
          shell: bash

    steps:
        # Connects runner to network
        - name: Setup WireGuard
          run: |
              sudo apt install resolvconf wireguard
              echo "${{ secrets.WG_CONFIG }}" > wg.conf
              sudo chmod 600 wg.conf
              sudo wg-quick up ./wg.conf
        # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v3
       # Install the latest version of Terraform CLI 
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: "1.13.1"

        - name: Generate Backend Config
          run: |
            cat > backend.hcl << EOF
            bucket = "${{ vars.BUCKET }}"
            key    = "${{ vars.KEY }}"
            region = "${{ vars.REGION }}"
            endpoints = {
              s3 = "${{ vars.ENDPOINT }}"
            }
            skip_credentials_validation = true
            skip_metadata_api_check     = true
            skip_region_validation      = true
            skip_requesting_account_id  = true
            EOF
     # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
        - name: Terraform Init
          id: init
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: terraform init -backend-config=backend.hcl
    
    
        # Run a terraform validate
        - name: Terraform Validate
          id: validate
          # Run even if formatting fails
          if: success() || failure()
          run: terraform validate -no-color



        - name: Terraform Plan
          id: plan
          env:
            TF_VAR_token_id: ${{ secrets.TF_VAR_TOKEN_ID }}
            TF_VAR_token_secret: ${{ secrets.TF_VAR_TOKEN_SECRET }} 
            TF_VAR_TRAEFIK_ENV: ${{ secrets.TF_VAR_TRAEFIK_ENV }}
            TF_VAR_HOMELABV2_SECRET: ${{ secrets.TF_VAR_HOMELABV2_SECRET }}        
          run: terraform plan -input=false -no-color -out=tfplan && terraform show -no-color tfplan
          
        - name: Run Checkov action
          id: checkov
          uses: bridgecrewio/checkov-action@master
          with: 
            framework: terraform
            
        - name: Upload SARIF file
          if: success() || failure()
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: results.sarif
            category: checkov
    
        - name: Add Plan Comment
          if: steps.plan.outcome == 'success'
          uses: actions/github-script@v6
          env:
            PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const output = `#### Terraform Initialization \`${{ steps.init.outcome }}\`
              #### Terraform Validation ${{ steps.validate.outputs.stdout }}
              #### Terraform Plan \`${{ steps.plan.outcome }}\`
          
              <details><summary>Show Plan</summary>
              
              \`\`\`${process.env.PLAN}\`\`\`
              
              </details>
              
              *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
                
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
    
        - name: Post Plan Failure 
          if: steps.plan.outcome == 'failure'
          uses: actions/github-script@v6
          env:
            PLAN_FAIL: "terraform\n${{ steps.plan.outputs.stderr }}"
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const output = `#### Terraform Plan \`${{ steps.plan.outcome }}\`
          
              <details><summary>Show Plan Error</summary>
              
              \`\`\`${process.env.PLAN_FAIL}\`\`\`
              
              </details>
              
              *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
                
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
