name: Push to feature branch

on:
  push:
    branches:
      - 'main'
env:
  TF_LOG: INFO
  TF_INPUT: false

jobs: 
  terraform-apply:
    runs-on: ubuntu-latest
    name: 'Terraform apply'
    environment: production
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    # Set the working directory to vnet for the config files
    defaults:
        run:
          shell: bash

    steps:
        # Connects runner to network
        - run: |
              sudo apt install resolvconf wireguard
              echo "${{ secrets.WG_CONFIG }}" > wg.conf
              sudo chmod 600 wg.conf
              sudo wg-quick up ./wg.conf
        # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v3
       # Install the selected version of Terraform CLI 
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: ${{ secrets.TERRAFORM_VERSION }}
    
     # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
        - name: Terraform Init
          id: init
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            REGION: ${{ vars.REGION }}
            BUCKET: ${{ vars.BUCKET }}
            KEY: ${{ vars.KEY }}
          run: terraform init --backend-config="access_key=$AWS_ACCESS_KEY_ID" --backend-config="secret_key=$AWS_SECRET_ACCESS_KEY" --backend-config="region=$REGION" --backend-config="bucket=$BUCKET" --backend-config="key=$KEY"
    
    
        # Run a terraform validate
        - name: Terraform Validate
          id: validate
          # Run even if formatting fails
          if: success() || failure()
          run: terraform validate -no-color



        - name: Terraform Plan
          id: plan
          env:
            TF_VAR_token_id: ${{ secrets.TF_VAR_TOKEN_ID }}
            TF_VAR_token_secret: ${{ secrets.TF_VAR_TOKEN_SECRET }}           
          run: terraform plan -input=false -no-color -out=tfplan && terraform show -no-color tfplan
    
        - name: Reformat Plan
          if: steps.plan.outcome == 'success'
          run: |
            echo '${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}' \
            | sed -E 's/^([[:space:]]+)([-+])/\2\1/g' > plan.txt          
        - name: Put Plan in Env Var
          if: steps.plan.outcome == 'success'
          run: |
            PLAN=$(cat plan.txt)
            echo "PLAN<<EOF" >> $GITHUB_ENV
            echo "$PLAN" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV 
        - name: Terraform Apply
          id: apply
          continue-on-error: true
          if: steps.plan.outcome == 'success'
          env:
            TF_VAR_token_id: ${{ secrets.TF_VAR_TOKEN_ID }}
            TF_VAR_token_secret: ${{ secrets.TF_VAR_TOKEN_SECRET }}      
          run: terraform apply -auto-approve -input=false -no-color tfplan



        - name: Post Plan and Apply to GitHub PR
          if: steps.plan.outcome == 'success' && steps.apply.outcome == 'success'
          uses: mshick/add-pr-comment@v1
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            repo-token-user-login: 'github-actions[bot]'
            message: |
              Applying **Infra**:
              <details><summary>Show Apply</summary>
              
              ```
              ${{ steps.apply.outputs.stdout }}
              ```
              
              </details>
        - name: Post Plan Failure
          if: steps.plan.outcome == 'failure'
          uses: mshick/add-pr-comment@v1
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            repo-token-user-login: 'github-actions[bot]'
            message: |
              Plan failed for **Infra**:
              <details><summary>Show Plan Fail</summary>
              
              ```
              ${{ steps.plan.outputs.stderr }}
              ```
              
              </details>
        - name: Post Apply Failure
          if: steps.apply.outcome == 'failure'
          uses: mshick/add-pr-comment@v1
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            repo-token-user-login: 'github-actions[bot]'
            message: |
              Apply failed for **Infra**:
              <details><summary>Show Apply Fail</summary>
              
              ```
              ${{ steps.apply.outputs.stderr }}
              ```
              
              </details>
